No Lists of Pointers for By-Pod Status Fields
open-policy-agent/frameworks pull request #99
Opened 2020-10-26 18:10 UTC by rajibmitra

2020-10-26 18:37 UTC, rajibmitra commented
cc @maxsmythe  Please let me know if this looks good.

2020-10-28 17:18 UTC, maxsmythe approved these changes
LGTM

@ritazh or @sozercan LGTY?

2020-10-29 19:19 UTC, sozercan commented
doesn't `zz_generated.deepcopy.go` need to be regenerated too?

2020-10-29 19:45 UTC, maxsmythe commented
Good catch. I thought maybe there was just no diff, but it looks like this code assumes a list of pointers:

https://github.com/open-policy-agent/frameworks/blob/2e11d4556af8e785768f44222d3792cc845e5c06/constraint/pkg/apis/templates/v1beta1/zz_generated.deepcopy.go#L176-L191

Another thing I missed:

We should fix both v1alpha1 and v1beta1

2020-10-29 19:46 UTC, maxsmythe requested changes
Resetting approval b/c I missed the v1beta1 and deepcopy regen issues.

2021-04-12 21:56 UTC, sozercan commented
Closing this due to inactivity. Please feel free to re-open.

2021-04-12 21:56 UTC, closed without merging